### ISSUE TITLE
LiveView Native SwiftUI: Strange behavior with Picker and conditionally rendered Image elements

### ISSUE THREAD

**Issue by supernintendo** [liveview-native/liveview-client-swiftui#769] opened 2023-04-02 03:52 UTC
Using a `Picker` and a native binding to conditionally render content within a `case` statement can cause errors if that conditional content contains `Image` elements. The error seems to result from rendering any number of `Image` views and then updating the assigns so that when the LiveView re-renders there are less `Image` views than before:

https://user-images.githubusercontent.com/5893007/229330166-062f23fc-0502-40c9-b5a8-b9fa09b87852.mov

https://user-images.githubusercontent.com/5893007/229330174-78f5b357-e973-4b42-82f4-ebc33c9a1eba.mov

You can reproduce this with the `bleeding-edge` branch of the scratchboard repo ([link](https://github.com/liveview-native/scratchboard/tree/bleeding-edge)). It uses a forked version of this repo but the changes are mostly limited to adding new modifiers.

**Comment by carson-katri** [comment] 2023-04-03 14:26
Minimal example:

```elixir
defmodule AppWeb.IndexLive do
  use AppWeb, :live_view
  use LiveViewNative.LiveView

  def mount(_params, _session, socket) do
    {:ok, assign(socket, show: true)}
  end

  def render(assigns) do
    render_native(assigns)
  end

  def handle_event("hide", _params, socket) do
    {:noreply, assign(socket, :show, false)}
  end
end
```
```heex
<%= if @show do %>
  <Image system-name="ant" />
<% end %>
<Button phx-click="hide">Hide</Button>
```

**Comment by shadowfacts** [comment] 2023-04-03 21:04
So, this issue has to do with how Core generates diffs. Essentially, when you click the Hide button in @carson-katri's example, Core produces a patch list that changes the Image element into a Button and then removes the second Button, rather than just removing the Image. Because we store NodeRefs across document "generations", elements appear to change out from under views. This also causes issues (though not as severe) elsewhere, like when removing live forms.

Unfortunately, changing that behavior in Core for cases more complex than that example is a substantial refactor. The expected behavior (elements being able to move around in the tree, rather than being removed and re-added elsewhere) is at odds with how Core generates diffs by walking both old & new trees simultaneously. See [this Slack thread](https://dockyard.slack.com/archives/C02E1GA5THB/p1677870596585149?thread_ts=1677859075.459679&cid=C02E1GA5THB) for more details.

One possible way around that big refactor that could solve this issue (big emphasis on the "could", I have not fully thought this through) is having element changes be generate diffs that are a InsertAfter and a Remove patch, rather than a Replace patch. That would end up using a different ref for the new element, which solves the dangling observers issue that's the source of the crash here. However, the underlying issue would remain, and the new and old Buttons would still be distinct in terms of SwiftUI view identity (potentially resulting in the loss of view state, for other views).

cc @KronicDeth, thoughts on either possible refactor?

**Comment by KronicDeth** [comment] 2023-04-04 01:44
I would count this as a bug in Core because it doesn’t replicate the Morphdom algorithm correctly and we should fix it to handle the updates based on ID like morphdom.

**Comment by Bajix** [comment] 2023-06-30 23:21
On the core side, this issue is resolved by the [morphing algorithm](https://github.com/liveview-native/liveview-native-core/blob/9dc2e4d35bde3b6d4f363630c7649afb5f862b75/crates/core/src/diff/diff.rs) in PR https://github.com/liveview-native/liveview-native-core/pull/26 but will require additional work on the iOS side to support `Patch::Detach` and `Patch::InsertBefore`. In the new version, Morph is an iterator of patches, so using `VecDeque<Patch>` is now optional.

**Comment by supernintendo** [comment] 2023-07-03 16:35
This has been resolved in this repo as well. Closing...

**Comment by AZholtkevych** [comment] 2023-07-05 11:53
reopening since

**Closed** 2023-07-13 23:30 UTC
Labels: bug
